Blog_admin_home:
    pattern: /
    defaults: {_controller: blogBundle:admin:index}
    requirements:
         _method: GET

# Article
Blog_ajouter_article:
    pattern: /ajouter
    defaults: {_controller: blogBundle:adminArticle:ajouter}
    requirements:
         _method: GET|POST

Blog_editer_article:
    pattern: /[id]/editer
    defaults: {_controller: blogBundle:adminArticle:editer}
    requirements:
         id : \d+
         _method: GET|POST
Blog_supprimer_article:
    pattern: /[id]/supprimer
    defaults: {_controller: blogBundle:adminArticle:supprimer}
    requirements:
         id : \d+
         _method: DELETE

